### ISSUE TITLE
Loading an empty webpage

### ISSUE THREAD

**Issue by rpatel372** [absurdist/swagger-ui-in-webpack#1]
When I run npm start and open http://localhost:8080/, it seems to just be loading an empty webpage instead of the petstore example?

**Comment by absurdist** [comment]
Hi Reema,

Thanks for letting me know, I'll see if i can replicate it. 
Can I ask what operating system and version of node you're using.

If I can't make it happen on my machine I might need to ask you some debugging questions.
Thanks
Mat

**Comment by absurdist** [comment]
Hi,
seems Webpack's API had changed since i created this repo. I've updated and updated dependencies.
please let me know if that's working for you now.

**Comment by absurdist** [comment]
closing the issue.
